- hosts: localhost
  tasks:
# 가상 머신 만들기, 데이터 디스크 추가
    - name: Create VM == {{ vm_name }}
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        managed_disk_type: "{{ add_managed_disk_type }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ vm_name }}-nic"
        ## OS 디스크 이름
        os_disk_name: "{{ add_os_disk_name }}"
        ## OS 디스크 사이즈(일반적으로 C드라이브라고 보면 됨)
        os_disk_size_gb: "{{ add_os_disk_size }}"

        # image:
        #     offer: CentOS
        #     publisher: OpenLogic
        #     sku: '7.7'
        #     version: latest
        # image:
        #     offer: CentOS
        #     publisher: OpenLogic
        #     sku: '7_9-gen2'
        #     version: latest
        image:
            offer: 0001-com-ubuntu-server-jammy
            publisher: Canonical
            sku: 22_04-lts-gen2
            version: latest

        ## 데이터 디스크 추가 부분
        data_disks:
          - lun: 0
            name: "{{ add_disk_name }}"
            disk_size_gb: "{{ add_disk_size_gb }}"
            managed_disk_type: "{{ add_managed_disk_type }}"
            
        state: absent

# 가상 네트워크 인터페이스 카드 만들기
    - name: Create virtual network interface card == {{ vm_name }}-nic
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-nic"
        virtual_network: "{{ virtual_network_name }}"
        subnet: "{{ subnet_name }}"
#        public_ip_name: "{{ vm_public_ip_name }}"
        security_group: "{{ vm_name }}-nsg"
        state: absent

# 네트워크 보안 그룹 만들기
    - name: Create Network Security Group == {{ vm_name }}-nsg
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-nsg"
        state: absent

        # 서브넷 만들기
    - name: Add subnet == {{ subnet_prefixes }}
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_prefixes }}"
        virtual_network: "{{ virtual_network_name }}"

    # 가상네트워크 만들기
    - name: Create virtual network == {{ virtual_network_name }}
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network_name }}"
        address_prefixes: "{{ virtual_address_prefixes }}"
# 리소스 그룹 만들기
    - name: Create Azure VM  == {{ resource_group }}
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"