---
email_address: 'dudwlsqk1@naver.com'
blog_URL: 'https://blog.naver.com/dudwlsqk1'



remote_user: "{{ remote_user }}" # 접속 유저 적기

          # Nginx Docker 컨테이너 관련 설정 #

app_dir: nginx                   # nginx 디렉토리 명 적기
nginx_base_directory: "{{ nginx_base_directory }}" # nginx /homme 디렉토리 적기 EXTRA_VARS로 대체
nginx_reverse_proxy_config_directory: "{{ nginx_base_directory }}/conf.d" # conf.d 폴더 생성 
nginx_container_name: 'nginx' # nginx container 명 
nginx_docker_tag: 'latest' # nginx image tag 불러오기
nginx_dockerfile_path: "{{ nginx_base_directory }}/Dockerfile"
docker_network_name: "{{ docker_network_name }}"

          # nginx 설정 관련 모음 #
nginx_static_html_directory: 'defaults' # nginx html 저장 폴더명
nginx_sites_enabled_path: "{{ nginx_base_directory }}/sites-enabled"
nginx_log_dir_path: "/var/log/nginx"
nginx_reverse_proxy_proxies: []




          # Docker-container restart-docker-nginx 영역 실행시 적용될 설정들 #
nginx_exposed_ports:
  - '80'
  - '443'
nginx_published_ports:
  - '80:80'
  - '443:443'
nginx_exposed_volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/letsencrypt:/etc/letsencrypt
  - /var/www/letsencrypt:/var/www/letsencrypt
  - /var/log/nginx:/var/log/nginx
  - "{{ nginx_base_directory }}/nginx.conf:/etc/nginx/nginx.conf:ro"
  - "{{ nginx_base_directory }}/defaults:/usr/share/nginx/html:ro"
  - "{{ nginx_reverse_proxy_config_directory }}:/etc/nginx/conf.d:rw"
  - "{{ nginx_sites_enabled_path }}:/etc/nginx/sites-enabled:ro"

nginx_conf: |
  user  nginx;
  worker_processes auto;

  pid /var/run/nginx.pid;

  events {
      worker_connections  65535;
      multi_accept on;
      use epoll;
  }

  http {
      server_tokens off;
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log off;
      log_not_found off;
      error_log  /var/log/nginx/error.log crit;

      sendfile on;
      tcp_nodelay off;
      tcp_nopush off;
      keepalive_timeout  65;

      #gzip  on;

      include /etc/nginx/conf.d/*.conf;
      include /etc/nginx/conf.d/general-security-headers.conf;
      include /etc/nginx/sites-enabled/*;
  }
